# Internship Task 4

In [1]:
import numpy as np

1.Create a NumPy array with the following values: [1, 2, 3, 4, 5]. 

In [66]:
a = np.array([0,1,2,3,4,5]) #added 0 to change size to 6, as getting ValueError: cannot reshape array of size 5 into shape (2,3)

2.Create a NumPy array with the following values: [1, 2, 3, 4, 5].

In [37]:
print(a.shape)

(6,)


3.Reshape the array into a 2D array with 2 rows and 3 columns. Not possible as size must be 6.

In [38]:
a1 = a.reshape(2, 3)
print(a1)

[[0 1 2]
 [3 4 5]]


4.Print the shape of the new array.

In [62]:
print(a1.shape)

(2, 3)


5. Create a second NumPy array with the following values: [6, 7, 8, 9, 10].

In [67]:
b1 = np.arange(6,12,1) #increased element to 11 as reshape needed size 6 
print(b1)

[ 6  7  8  9 10 11]


In [69]:
b=b1.reshape(2,3) #reshaped b as ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
print(b)

[[ 6  7  8]
 [ 9 10 11]]


6. Concatenate the two arrays together horizontally. 7. Print the resulting array.

In [70]:
c=np.concatenate((a1,b),axis=1)
print(c)

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


8. Compute the resulting array's mean, median, and standard deviation.

In [50]:
mean=np.mean(c)
median=np.median(c)
sd=np.std(c)

In [55]:
print("Mean:",mean) 
print("Median:",median)
print("Standard deviation:",sd)

Mean: 5.5
Median: 5.5
Standard deviation: 3.452052529534663


In [73]:
a2=np.arange(1,6,1)
b2=np.arange(6,11,1)
print(a2,b2)
c1=c=np.concatenate((a2,b2)) #concatenate the arrays without reshape
print(c1)

[1 2 3 4 5] [ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [74]:
mean1=np.mean(c1)
print("Mean:",mean1) 
median1=np.median(c1)
print("Median:",median1)
sd1=np.std(c1)
print("Standard deviation:",sd1) #sd different if they are not reshaped using 0 and 11

Mean: 5.5
Median: 5.5
Standard deviation: 2.8722813232690143
